### ISSUE TITLE
puppet-netbeans 1.0.1

### ISSUE THREAD

**Issue by pongstr** [pongstr/boxen#41]
Boxen fails when using `puppet-netbeans 1.0.1`: for reasons I'm not really familiar with. 

@devcsrj do you think you can investigate why it does? Here's how to reproduce the issue:

> On fresh install OSX, run boxen after clone `./script/boxen --no-fde --default`

Not entirely sure whether `./script/nuke --all --force` method will also reproduce the issue but you can try. Thanks!

/cc @femee24 @itsvicsoto

**Comment by pongstr** [comment]
would it be okay to use `puppet-netbeans 1.0.0` for now?

**Comment by devcsrj** [comment]
@femee24 now installing NB via `brew-cask`

**Comment by pongstr** [comment]
fixed: 33e49eee998893246612680bf08b3b1a57ecf43a
