### ISSUE TITLE
Apps with no available puppets

### ISSUE THREAD

**Issue by femee24** [pongstr/boxen#53]
- [x] soapui: install via `package:appdmg`
- [x] talend
- [x] squirrel sql
- [x] sqlpowerarchitect: install via `package:zip`

**Comment by pongstr** [comment]
- talend: please specify version
- squirrelSql: isn't this an ide plugin? download artifact is a `.jar` file

**Comment by pongstr** [comment]
fixed with: dc13fb360067b1362a3ab13c9c978e5780f5c17f
