### ISSUE TITLE
team shiva: application

### ISSUE THREAD

**Issue by femee24** [pongstr/boxen#76]
//cc @femee24 @marinela25 please update when necessary

- [x] Adobe Creative Cloud
- [x] Adobe Reader
- [x] Cyberduck
- [x] Dashlane
- [x] FileZilla
- [x] iWork Keynote (should be default on OSX Installation)
- [x] Open Office
- [x] unrarX
- [x] vlc
- [x] winzip
- [x] yemuzip

**Comment by pongstr** [comment]
fixed with: 041d82865bc8c97884ae703fcbc2c69fbc7e583c close issue maybe? @femee24

**Comment by femee24** [comment]
ahh yes sir :) surely

**Comment by femee24** [comment]
ayy sorry... i mean ako na po mgcoclose pla...kasi further testing pa for standard user on production team

**Comment by pongstr** [comment]
copy :+1:
